name: cryptostat

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - name: Action - checkout
      uses: actions/checkout@v3

    - name: Setup yarn
      run: npm install yarn

    - name: Install dependencies
      run: yarn install

    - name: Uninstall Yarn
      if: always()
      run: npm uninstall yarn